# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-28 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0035_new_data_alternate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_data',
            name='in_main_database',
            field=models.BooleanField(default=False),
        ),
    ]
