# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0036_new_data_in_main_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_data',
            name='constant_in_orbyts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='new_data',
            name='state_in_orbyts',
            field=models.BooleanField(default=False),
        ),
    ]
